[workspace]
name = "cleanskate"
version = "0.1.0"
description = "Pandas-friendly access to figure skating scores"
channels = ["conda-forge"]
platforms = ["osx-arm64", "osx-64", "linux-64"]

[dependencies]
python = "3.12.*"
ipython = ">=9.0,<10"
pytest = ">=8.0,<9"
python-build = ">=1.4.4,<2"
hatchling = ">=1.29.0,<2"
twine = ">=6.2.0,<7"
matplotlib = ">=3.10.9,<4"
seaborn = ">=0.13.2,<0.14"

[pypi-dependencies]
cleanskate = { path = ".", editable = true }
pandas = ">=2.2"
platformdirs = ">=4.3"
pyarrow = ">=16.0"
requests = ">=2.32"

[tasks]
python = "python"
ipython = "ipython"
test = "pytest"
clean-dist = "rm -rf dist"
build = "python -m build"
check-dist = "twine check dist/*"
publish-testpypi = "twine upload --repository testpypi dist/*"
publish-pypi = "twine upload dist/*"
